name: CI/CD Pipeline

on:

push:

branches:

- main

jobs:

build-and-test:
    runs-on: ubuntu-latest

    name: Build and test

    steps:

    - uses: actions/checkout@v3

    - uses: bahmutov/npm-install@v1

    - run: npm run lint

    - run: npm run test
